// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSmyzooaELSs-iUcV9GZZvC00LYdEzG-Y',
    appId: '1:664115583084:web:23ddcc377e85b412f6e049',
    messagingSenderId: '664115583084',
    projectId: 'note-df3a2',
    authDomain: 'note-df3a2.firebaseapp.com',
    storageBucket: 'note-df3a2.firebasestorage.app',
    measurementId: 'G-L7D1J8P366',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXXeHCJ8vhWA5ins_hIsn46aLe3Ug5d9M',
    appId: '1:664115583084:android:ae8edc3a58954acaf6e049',
    messagingSenderId: '664115583084',
    projectId: 'note-df3a2',
    storageBucket: 'note-df3a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIRo6wlBMjk8gyTosHqngn3VlSFpWVvRI',
    appId: '1:664115583084:ios:9cd8e0692832f236f6e049',
    messagingSenderId: '664115583084',
    projectId: 'note-df3a2',
    storageBucket: 'note-df3a2.firebasestorage.app',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIRo6wlBMjk8gyTosHqngn3VlSFpWVvRI',
    appId: '1:664115583084:ios:9cd8e0692832f236f6e049',
    messagingSenderId: '664115583084',
    projectId: 'note-df3a2',
    storageBucket: 'note-df3a2.firebasestorage.app',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSmyzooaELSs-iUcV9GZZvC00LYdEzG-Y',
    appId: '1:664115583084:web:80e65665e700cd52f6e049',
    messagingSenderId: '664115583084',
    projectId: 'note-df3a2',
    authDomain: 'note-df3a2.firebaseapp.com',
    storageBucket: 'note-df3a2.firebasestorage.app',
    measurementId: 'G-VVHPZGFTWF',
  );
}
